export default {
  ALIGN : 'ALIGN',
  SHOW_ALIGN_MODAL : 'SHOW_ALIGN_MODAL',
  HIDE_ALIGN_MODAL : 'HIDE_ALIGN_MODAL',
  HIDE_CREATE_BUTTON: 'HIDE_CREATE_BUTTON',
  FINALIZE_CHARACTER: 'FINALIZE_CHARACTER',
  SHOW_DICE: 'SHOW_DICE',
  SHOW_PROFILE: 'SHOW_PROFILE'
};
